In [1]:
import numpy as np
## create array using numpy
# creating 1D array

arr1=np.array([1,2,3,4,5])
print(arr1)
print(type(arr1))
print(arr1.shape)

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [3]:
arr2=np.array([1,2,3,4,5])
arr2.reshape(1,5)

array([[1, 2, 3, 4, 5]])

In [ ]:
#2d array
arr2=np.array([[9,2,3,4,5],[9,2,4,6,8]])
print(arr2)
print(arr2.shape)

[[9 2 3 4 5]
 [9 2 4 6 8]]
(2, 5)


In [ ]:
# conversion of 1d array to 2d array
np.arange(0,10,2).reshape(5,1)

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [10]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [11]:
#identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
#attributes of numpy
arr=np.array([[1,2,3],[4,5,6]])
print("Array:\n",arr)
print("Shape:",arr.shape) #output:(2,3)
print("Number of dimensions:",arr.ndim) #output:2
print("Size(number of elements):",arr.size) #output:6
print("Data type:",arr.dtype)#output int 64
print("item size (in bytes):", arr.itemsize) #output:8

Array:
 [[1 2 3]
 [4 5 6]]
Shape: (2, 3)
Number of dimensions: 2
Size(number of elements): 6
Data type: int64
item size (in bytes): 8


In [13]:
#numpy vectorized operation
arr1=np.array([1,2,3,4,5])
arr2=np.array([6,7,8,9,10])

#element wise addition
print("Addition:",arr1+arr2)

#element wise subtraction
print("Subtraction:",arr1-arr2)

Addition: [ 7  9 11 13 15]
Subtraction: [-5 -5 -5 -5 -5]


In [15]:
#unvieral functions
arr=np.array([2,3,4,5,6])
#square root
print(np.sqrt(arr))
#exponential
print(np.exp(arr))
#sine
print(np.sin(arr))

[1.41421356 1.73205081 2.         2.23606798 2.44948974]
[  7.3890561   20.08553692  54.59815003 148.4131591  403.42879349]
[ 0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155 ]


In [17]:
#array slicing and indexing
arr=np.array([[1,2,3,5],[4,5,6,7],[8,9,11,10]])
print("Array:\n",arr)

Array:
 [[ 1  2  3  5]
 [ 4  5  6  7]
 [ 8  9 11 10]]
